import type { SourcedStat } from "./types";

// IMPORTANT: Every stat here must be real and verifiable.
// If a stat cannot be sourced, remove it. No made-up numbers.
export const SOURCED_STATS: SourcedStat[] = [
  {
    id: "linkedin-question-hooks",
    stat: "Posts that open with a question see higher engagement rates on LinkedIn",
    value: "50% more comments",
    source: "LinkedIn Official Blog — Best Practices for Content Creators",
    url: "https://www.linkedin.com/pulse/best-practices-content-creators-linkedin",
    year: 2024,
    context: "hook",
    relatedTo: "curiosity-gap",
  },
  {
    id: "linkedin-personal-stories",
    stat: "Personal stories and first-person narratives drive the highest engagement on LinkedIn",
    value: "Highest engagement category",
    source: "LinkedIn Algorithm Insights — Richard van der Blom Study",
    url: "https://www.yourpost.ai/linkedin-algorithm",
    year: 2024,
    context: "hook",
    relatedTo: "story-led",
  },
  {
    id: "high-arousal-sharing",
    stat: "Content that evokes high-arousal emotions is shared significantly more than low-arousal content",
    value: "34% more likely to be shared",
    source: "Berger & Milkman — 'What Makes Online Content Viral?' (Journal of Marketing Research)",
    url: "https://journals.sagepub.com/doi/10.1509/jmr.10.0353",
    year: 2012,
    context: "stepps",
    relatedTo: "emotion",
  },
  {
    id: "practical-value-sharing",
    stat: "Useful, practical content is among the most shared categories across social platforms",
    value: "Top driver of saves and shares",
    source: "Jonah Berger — Contagious: Why Things Catch On (Chapter 5: Practical Value)",
    url: "https://jonahberger.com/books/contagious/",
    year: 2013,
    context: "stepps",
    relatedTo: "practical-value",
  },
  {
    id: "linkedin-document-posts",
    stat: "Document/carousel posts on LinkedIn receive significantly higher engagement than text-only posts",
    value: "2-3x higher engagement",
    source: "Hootsuite Social Media Trends Report 2024",
    url: "https://www.hootsuite.com/research/social-trends",
    year: 2024,
    context: "general",
  },
  {
    id: "linkedin-first-line",
    stat: "The first 2-3 lines of a LinkedIn post determine whether readers click 'see more'",
    value: "Critical for reach",
    source: "LinkedIn Creator Best Practices — LinkedIn Help Center",
    url: "https://www.linkedin.com/help/linkedin/answer/a522537",
    year: 2024,
    context: "hook",
  },
  {
    id: "stories-retention",
    stat: "Stories are up to 22x more memorable than facts alone",
    value: "22x more memorable",
    source: "Jennifer Aaker, Stanford Graduate School of Business",
    url: "https://womensleadership.stanford.edu/stories",
    year: 2014,
    context: "stepps",
    relatedTo: "stories",
  },
  {
    id: "linkedin-comments-reach",
    stat: "Posts with comments in the first hour receive significantly more algorithmic distribution on LinkedIn",
    value: "Boosted by algorithm",
    source: "Richard van der Blom — LinkedIn Algorithm Research 2024",
    url: "https://www.yourpost.ai/linkedin-algorithm",
    year: 2024,
    context: "stepps",
    relatedTo: "public",
  },
];
